openapi: 3.0.3

info:
  version: "1.0"
  title: Сервис пользователей

servers:
  - url: http://localhost:8080/

paths:
# USER
  /register:
    post:
      summary: Регистрация нового пользователя
      description: Создаёт нового пользователя на основе предоставленного логина и пароля.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
                - login
                - password
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
        '400':
          description: Невалидные данные / пользователь существует
        '500':
          description: Внутренняя ошибка сервера

  /login:
    post:
      summary: Вход пользователя
      description: Аутентифицирует пользователя на основе логина и пароля, и отправляет токен для аутентификации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
                - login
                - password
      responses:
        '200':
          description: Вход успешен
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Сессионный cookie
        '400':
          description: Невалидные данные
        '500':
          description: Внутренняя ошибка сервера

  /update-info:
    put:
      summary: Обновление данных пользователя
      description: Обновляет данные о пользователе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                birth_day:
                  type: string
                  format: date
                mail:
                  type: string
                phone_number:
                  type: string
      responses:
        '204':
          description: Данные успешно обновлены
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '500':
          description: Внутренняя ошибка сервера
      security:
        - cookieAuth: []

#TASK
  /create-task:
    post:
      summary: Добавление задачи
      description: Создаёт новую задачу с заданными полями
      parameters:
        - name: "jwt"
          in: "header"
          schema:
            type: "string"
          description: "JWT передается через cookie в заголовке."
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Задача успешно создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '500':
          description: Внутренняя ошибка сервера
      security:
        - cookieAuth: []

  /task:
    get:
      summary: Получение задачи
      description: Даёт информацию о задаче по ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Данные о задаче успешно получены
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  author:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  creation_time:
                    type: string
                    format: date-time
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '403':
          description: Недостаточно прав, чтобы получить данную задачу
        '500':
          description: Внутренняя ошибка сервера / Передан несуществующий ID
      security:
        - cookieAuth: []

    delete:
      summary: Удаление задачи
      description: Удаляет задачу по ID. Удалить можно только свои задачи
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Задача успешно удалена
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '403':
          description: Недостаточно прав, чтобы удалить задачу
        '500':
          description: Внутренняя ошибка сервера / Передан несуществующий ID
      security:
        - cookieAuth: []

  /update-task-info:
    put:
      summary: Обновление задачи
      description: Меняет название и/или содержание задачи по ID. Менять можно только свои задачи
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ID:
                  type: integer
                title:
                  type: string
                content:
                  type: string
      responses:
        '204':
          description: Задача успешно обновлена
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '403':
          description: Недостаточно прав, чтобы изменить задачу
        '500':
          description: Внутренняя ошибка сервера / Передан несуществующий ID
      security:
        - cookieAuth: []

  /tasks:
    get:
      summary: Получение задач с пагинацией
      description: Получение задач по offset'у и размером batch'а. Кроме задач возвращает offset для получения следующего batch'а задач
      parameters:
        - in: query
          name: batch_size
          schema:
            type: integer
          required: true
        - in: query
          name: offset
          schema:
            type: integer
          required: true

      responses:
        '200':
          description: Задачи успешно получены
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        author:
                          type: string
                        title:
                          type: string
                        content:
                          type: string
                        creation_time:
                          type: string
                          format: date-time
                  offset:
                    type: integer
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '500':
          description: Внутренняя ошибка сервера
      security:
        - cookieAuth: []

  /like:
    post:
      summary: Добавление лайка на задачу
      description: Добавляет лайк на задачу по ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Лайк поставлен успешно
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '500':
          description: Внутренняя ошибка сервера
      security:
        - cookieAuth: []

  /view:
    post:
      summary: Добавление просмотра на задачу
      description: Добавляет просмотр на задачу по ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Просмотр добавлен успешно
        '400':
          description: Невалидные данные
        '401':
          description: Не переданы cookie
        '500':
          description: Внутренняя ошибка сервера
      security:
        - cookieAuth: []


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt
      description: Авторизация через JWT
