@startuml context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/user.puml
!include FONTAWESOME/desktop.puml

Person(user, "User", "Want to use task tracker", $sprite="user")
Container(spa, "Task Tracker", "website", "The main interface that the user interacts with", $sprite="desktop")

Rel(user, spa, "Uses")

SHOW_FLOATING_LEGEND()

@enduml